spring:
  application:
    name: mubu-backend

  servlet:
    multipart:
      # 업로드 가능한 단일 이미지 최대 크기
      max-file-size: 10MB

      # 요청 전체 최대 크기
      max-request-size: 10MB

server:
  port: 8080

mubu:
  service:
    version: 0.0.1
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
