spring:
  application:
    name: mubu-backend

server:
  port: 8080

mubu:
  service:
    version: 0.0.1
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

